<?php

/**
 * @file
 * Main module for OAuth login provider
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function oauthloginprovider_ctools_plugin_api($module, $api) {
  if ($module == 'services' && $api == 'services') {
    return array('version' => 3);
  }
  if ($module == 'oauth_common' && $api == 'oauth') {
    return array('version' => 1);
  }
}

/**
 * Implementation of hook_services_resources().
 */
function oauthloginprovider_services_resources() {
  $res = array(
    'oauthlogin' => array(
      'actions' => array(
        'info' => array(
          'access callback' => 'user_access',
          'access arguments' => array('access content'),
          'access arguments append' => false,
          'args' => array(),
          'help' => 'Retrieves information about the current user',
          'callback' => 'oauthloginprovider_user_info_action',
        ),
      ),
    ),
  );
  return $res;
}

function oauthloginprovider_user_info_action() {
  global $user;

  $data = (array)$user;
  unset($data['pass']);

  return (object)$data;
}
