<?php
// replace strings with _REPLACE in them

		function supportfunc_sort_view_result($a,$b) {
			global $_log_for_donation_register_views_pre_render;
			global $find_users_weight_by_uid;
			
			//$uidForLog = $a->uid." = ".$a->users_name."\n";
			//file_put_contents($_log_for_donation_register_views_pre_render, $uidForLog, FILE_APPEND);
			if ( array_key_exists($a->uid, $find_users_weight_by_uid) && array_key_exists($b->uid, $find_users_weight_by_uid) ) {
				if($find_users_weight_by_uid[$a->uid] == $find_users_weight_by_uid[$b->uid]) {
			        return 0 ;
			    } 
 				return ($find_users_weight_by_uid[$a->uid] > $find_users_weight_by_uid[$b->uid]) ? -1 : 1;
				//file_put_contents($_log_for_donation_register_views_pre_render, "if ake passed \n", FILE_APPEND);
			} else {
				return 0;
				//file_put_contents($_log_for_donation_register_views_pre_render, "if ake failed - in else \n", FILE_APPEND);
			}
		}

function donation_register_views_pre_render(&$view) {
	global $_log_for_donation_register_views_pre_render;
	$_log_for_donation_register_views_pre_render = '_REPLACE/path/to/log.txt';
	$log = $_log_for_donation_register_views_pre_render;
	file_put_contents($log, "==OLD LOG OVERWRITTEN==\n");
	
		
	
	if ($view->name == 'past_donations' || $view->name == 'planned_donations') {
		file_put_contents($log, "if triggered\n", FILE_APPEND);
		//file_put_contents($log, print_r($view->result, TRUE), FILE_APPEND);
		
		$db = mysql_connect("localhost", 'USERNAME_REPLACE', 'PASSWORD_REPLACE');
		mysql_select_db("DB_REPLACE",$db); // **NB** Check this is the right database, and change it when switch to ***live*** site
		mysql_set_charset('utf8',$db); 
		
		/* NEW PLAN:
		- fetch user id order in my custom mysql way and then apply it
		*/
		
		// - fetch user id order in my custom mysql way
		/*
		global $users_main;
		$users_main = array();
		$find_users_key1_by_uid = array();
		*/
		global $find_users_weight_by_uid;
		$find_users_weight_by_uid = array();
		$result = mysql_query("SELECT profile.uid, field_data_field_weighting.field_weighting_value FROM profile
		INNER JOIN field_data_field_weighting ON profile.pid = field_data_field_weighting.entity_id
		ORDER BY field_data_field_weighting.field_weighting_value DESC
		");
		$i = 0; // have $i be key to preserve ORDER BY
		while ($row = mysql_fetch_row($result)) {
			// The uid is the test for merging. It doesn't need to be a bottom-level key, as it's not the test-condition for mergi ????
			//$users_main[$i]['uid'] = $row[0]; // have $i be key to preserve ORDER BY
			// $users_main[$i]['weight'] = $row[1]; // have $i be key to preserve ORDER BY
			//$find_users_key1_by_uid[$row[0]] = $i;
			$find_users_weight_by_uid[$row[0]] = $row[1];
			$i++;
		}
		
		// 
		usort($view->result, 'supportfunc_sort_view_result');
		file_put_contents($log, print_r($view->result, TRUE), FILE_APPEND);


		/* commented out cos exceeds max execution time
		$transfer_array1 = array();
		$i = 0;
		foreach ($users_main as $user_main) {
			while ($i <= max(array_keys($view->result))) { // not a for loop, so $i is accessible within
				if ($view->result[$i]->uid == $user_main['uid']) {
					$transfer_array1[] = clone $view->result[$i];
				}
			}
		}
		
		file_put_contents($log, print_r($transfer_array1, TRUE), FILE_APPEND);
		
		*/
		
		
		
		
		/* OLD PLAN:
		- loop though v-r by i-increment
			- while doing so, create transfer_array1 with weight the key and i the value, then sort by key (ksort())
				- ACTUALLY, MAY NEED TO MAKE user_id THE VALUE, OR AN ADDITIONAL VALUE
		- recreate result with transfer_array2[] = clone v-r[transfer_array[weight]]
		- overwrite v-r: v-r = transfer_array2[]
		
		
		
		
		$transfer_array1 = array();
		$i = 0;
		while ($i <= max(array_keys($view->result))) { // not a for loop, so $i is accessible within
			//$debug_array_or_object = $view->result[$i]->_field_data['profile_users_pid']['entity'];
			if (isset($view->result[$i]->_field_data['profile_users_pid']['entity']->field_weighting)) {
				$weight = $view->result[$i]->_field_data['profile_users_pid']['entity']->field_weighting['und'][0]['value'];
				file_put_contents($log, "$weight \n", FILE_APPEND);
				$transfer_array1[$weight] = $i; // actually make this either user id or even better $i for the 'donations' profile 
			}
			$i++;
		}
		
		$transfer_array2 = array();
		foreach ($transfer_array1 as $to_transfer) {
			
		}
		/OLD PLAN CODE
		*/
		
	}
//	$view->result = $view->result;
}
